In [21]:
from pandas import DataFrame
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt

In [22]:
 my_data=[['slashdot','USA','yes',18,'None'], 

['google','France','yes',23,'Premium'], 

['digg','USA','yes',24,'Basic'], 

['kiwitobes','France','yes',23,'Basic'], 

['google','UK','no',21,'Premium'], 

['(direct)','New Zealand','no',12,'None'], 

['(direct)','UK','no',21,'Basic'], 

['google','USA','no',24,'Premium'], 

['slashdot','France','yes',19,'None'], 

['digg','USA','no',18,'None'], 

['google','UK','no',18,'None'], 

['kiwitobes','UK','no',19,'None'], 

['digg','New Zealand','yes',12,'Basic'], 

['slashdot','UK','no',21,'None'], 

['google','UK','yes',18,'Basic'], 

['kiwitobes','France','yes',19,'Basic']]

In [31]:
data=pd.DataFrame(my_data,columns=['from','area','faq','visits','service'])

         from         area  faq  visits  service
0    slashdot          USA  yes      18     None
1      google       France  yes      23  Premium
2        digg          USA  yes      24    Basic
3   kiwitobes       France  yes      23    Basic
4      google           UK   no      21  Premium
5    (direct)  New Zealand   no      12     None
6    (direct)           UK   no      21    Basic
7      google          USA   no      24  Premium
8    slashdot       France  yes      19     None
9        digg          USA   no      18     None
10     google           UK   no      18     None
11  kiwitobes           UK   no      19     None
12       digg  New Zealand  yes      12    Basic
13   slashdot           UK   no      21     None
14     google           UK  yes      18    Basic
15  kiwitobes       France  yes      19    Basic

In [43]:
# 将文字转化为数字
col_from=pd.Categorical.from_array(data['from']) 
col_area=pd.Categorical.from_array(data['area'])
col_faq=pd.Categorical.from_array(data['faq'])
col_visits=pd.Categorical.from_array(data['visits'])
col_service=pd.Categorical.from_array(data['service'])

data['from']=col_from.codes
data['area']=col_area.codes
data['faq']=col_faq.codes
data['visits']=col_visits.codes
data['service']=col_service.codes

    from  area  faq  visits  service
0      4     3    1       1        1
1      2     0    1       4        2
2      1     3    1       5        0
3      3     0    1       4        0
4      2     2    0       3        2
5      0     1    0       0        1
6      0     2    0       3        0
7      2     3    0       5        2
8      4     0    1       2        1
9      1     3    0       1        1
10     2     2    0       1        1
11     3     2    0       2        1
12     1     1    1       0        0
13     4     2    0       3        1
14     2     2    1       1        0
15     3     0    1       2        0

In [44]:
x=data.iloc[:,:4].as_matrix().astype(int)
y=data.iloc[:,4].as_matrix().astype(int)

(array([[4, 3, 1, 1],
        [2, 0, 1, 4],
        [1, 3, 1, 5],
        [3, 0, 1, 4],
        [2, 2, 0, 3],
        [0, 1, 0, 0],
        [0, 2, 0, 3],
        [2, 3, 0, 5],
        [4, 0, 1, 2],
        [1, 3, 0, 1],
        [2, 2, 0, 1],
        [3, 2, 0, 2],
        [1, 1, 1, 0],
        [4, 2, 0, 3],
        [2, 2, 1, 1],
        [3, 0, 1, 2]]),
 array([1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0]))

In [45]:
#拆分训练数据与测试数据 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.6)

In [46]:
####knn最邻近算法####
#训练KNN分类器 
clf = KNeighborsClassifier(algorithm='kd_tree')
clf.fit(x_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [51]:
#测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print 'KNN分类器模型准确率',(np.mean( answer == y_test))
print classification_report(y_test,answer)

[[0 2 0 3]
 [4 3 1 1]
 [2 2 0 1]
 [3 0 1 4]]
[0 1 0 1]
[0 1 1 0]
KNN分类器模型准确率 0.5
             precision    recall  f1-score   support

          0       0.50      0.50      0.50         2
          1       0.50      0.50      0.50         2

avg / total       0.50      0.50      0.50         4

In [52]:
####贝叶斯分类器####
#训练贝叶斯分类器
clf = BernoulliNB() 
clf.fit(x_train,y_train)


#测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean( answer == y_test))
print(classification_report(y_test, answer, target_names = ['低', '高']))

[[0 2 0 3]
 [4 3 1 1]
 [2 2 0 1]
 [3 0 1 4]]
[1 0 1 0]
[0 1 1 0]
0.5
             precision    recall  f1-score   support

        低       0.50      0.50      0.50         2
        高       0.50      0.50      0.50         2

avg / total       0.50      0.50      0.50         4

In [56]:
####决策树####
from sklearn.tree import DecisionTreeClassifier as DTC
dtc = DTC(criterion='entropy') #建立决策树模型，基于信息熵
dtc.fit(x_train, y_train) #训练模型

#导入相关函数，可视化决策树。
#导出的结果是一个dot文件，需要安装Graphviz才能将它转换为pdf或png等格式。
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO
with open("tree.dot", 'w') as f:
  f = export_graphviz(dtc, out_file = f)


#测试结果
answer = dtc.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean( answer == y_test))
print(classification_report(y_test, answer))

[[0 2 0 3]
 [4 3 1 1]
 [2 2 0 1]
 [3 0 1 4]]
[2 1 1 2]
[0 1 1 0]
0.5
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         2
          1       1.00      1.00      1.00         2
          2       0.00      0.00      0.00         0

avg / total       0.50      0.50      0.50         4

In [58]:
####SVM####
from sklearn.svm import SVC
clf =SVC()
clf.fit(x_train, y_train)  

#测试结果
answer = clf.predict(x_test)
print(x_test)
print(answer)
print(y_test)
print(np.mean( answer == y_test))
print(classification_report(y_test, answer))

[[0 2 0 3]
 [4 3 1 1]
 [2 2 0 1]
 [3 0 1 4]]
[1 1 1 2]
[0 1 1 0]
0.5
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         2
          1       0.67      1.00      0.80         2
          2       0.00      0.00      0.00         0

avg / total       0.33      0.50      0.40         4